name: julia
on:
  workflow_dispatch:
  push:
    branhces:
      - main
    paths:
      - julia/**
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: default-make-rule
        run: cd julia && make


